---
title: "Title: Categorical Analysis on Diabetes"
author: "Authors: Liangjie Lu, Weiting Lin, Luyang Zhang, Yaocao Chen"
date: "Date: 2024-02-19"
output: html_document
---

```{r, setup, results='hide', message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(knitr)
library(kableExtra)
library(stats)
library(zoo)
library(lubridate)
library(tseries)
library(forecast)
library(funtimes)
```

## Data Loading and Preprocessing

```{r}
diabetes.dat <- read.csv("diabetes.csv", header = TRUE)

# Transform data Outcome from 0 to 'Diabetes' and "1" to 'No_Diabetes'
diabetes.dat$Outcome.val <- diabetes.dat$Outcome
diabetes.dat$Outcome[diabetes.dat$Outcome == "0"] <- 'Diabetes'
diabetes.dat$Outcome[diabetes.dat$Outcome == "1"] <- 'No_Diabetes'

diabetes.dat$Outcome <- diabetes.dat$Outcome %>% as.factor
diabetes.dat$BMI.ord <- diabetes.dat$BMI %>% cut(
  breaks = c(-Inf, 18.5, 24.9, 29.9, Inf),
  labels = c("Underweight", "Healthy Weight","Overweight", "Obesity"),
  right = FALSE) %>% factor(levels = c("Underweight", "Healthy Weight", "Overweight", "Obesity"))



```

## Data Visualization

```{r}
BMI.categories <- diabetes.dat$BMI.ord
Outcome <- diabetes.dat$Outcome

# Create a 2-way table
table.dat <- table(BMI.categories,Outcome)



kable(table.dat, "html", caption = "BMI Categories vs. Diabetes Outcome") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F) %>%
  add_header_above(c(" " = 1, "Outcome" = 2))


# Generate mosaic plot
mosaicplot(table.dat, main = "BMI Categories vs. Diabetes Outcome", col = c("lightblue", "salmon"),
           xlab = "BMI Category", ylab = "Outcome")
```

## Test for Independence

### X\^2 and G\^2

```{r}
# not merge
final_data=diabetes.dat[c("Outcome","BMI.ord")]

# Merge Obesity/ not Obesity
# Transform data BMI_categories to character type
final_data$BMI.ord <- as.character(final_data$BMI.ord)
final_data$BMI.ord[final_data$BMI.ord =="Underweight"]<-"No Obesity"
final_data$BMI.ord[final_data$BMI.ord =="Healthy Weight"]<-"No Obesity"
final_data$BMI.ord[final_data$BMI.ord == "Overweight"]<-"Obesity"


# Transform data Outcome from 0 to 'Diabetes' and "1" to 'No_Diabetes'
#final_data$Outcome[final_data$Outcome == "0"] <- 'Diabetes'
#final_data$Outcome[final_data$Outcome == "1"] <- 'No_Diabetes'
#final_data$Outcome<- as.character(final_data$Outcome)

# Pivot table to show data after being grouped by Diabetes and BMI categories variables
pivot_table <- final_data %>%
  group_by(BMI.ord, Outcome) %>%
  summarise(Count = n(), .groups = 'drop') 

pivot_table<-tidyr::pivot_wider(pivot_table, names_from = Outcome, values_from = Count)

# Transform vales of number of people with Diabetes or without Diabetes to numeric
pivot_table$Diabetes<-as.numeric(pivot_table$Diabetes)
pivot_table$No_Diabetes<-as.numeric(pivot_table$No_Diabetes)

# Calculate the total number of people cross four different BMI categories
pivot_table$total=pivot_table$Diabetes+pivot_table$No_Diabetes

# Calculate the total number of people cross Two different Diabetes outcomes
pivot_table[nrow(pivot_table)+1, ] <- list("total",sum(pivot_table$Diabetes),sum(pivot_table$No_Diabetes),sum(pivot_table$total))



# Arrange BMI categories with order "Underweight", "Healthy Weight","Overweight", "Obesity", "total" to better visulization and understanding

## not merge
#pivot_table$BMI.ord <- factor(pivot_table$BMI.ord, 
#                                     levels = c("Underweight", "Healthy Weight",
#                                                "Overweight","Obesity","total"))

# merge
pivot_table$BMI.ord <- factor(pivot_table$BMI.ord, 
                                     levels = c("No Obesity","Obesity","total"))

pivot_table <- pivot_table %>% 
  arrange(match(BMI.ord, levels(BMI.ord)))

# final result 


pivot_table %>%
  kable("html", booktabs = TRUE, caption = "Summary of BMI Categories") %>%
  kable_styling(position = "center", full_width = FALSE) %>%
  column_spec(1, bold = TRUE, border_right = TRUE) %>%
  add_header_above(c(" " = 1, "Outcomes" = 2, " " = 1))

```

$\mu_{ij}=n_{i+}n_{+j}$

```{r}
# mu_ij=ni+*n+j/n++
mu_ij<-pivot_table
for( i in 1:(nrow(pivot_table)-1)){
  for(j in 2:(ncol(pivot_table)-1)){
    mu_ij[i,j]<-pivot_table[i,ncol(pivot_table)]*pivot_table[nrow(pivot_table),j]/pivot_table[nrow(pivot_table),ncol(pivot_table)]
    
  }
}

mu_ij<-mu_ij[1:(nrow(mu_ij) - 1),1:(ncol(mu_ij) - 1)]
mu_ij%>%
  kable("html", booktabs = TRUE, caption = "$\\mu_{ij}$ table: $\\frac{n_{i+} + n_{+j}}{n_{++}}$") %>%
  kable_styling(full_width = F, position = "center") %>%
  column_spec(1, bold = TRUE, border_right = TRUE)
  
```

```{r}
#pearson table x^2
pearson_table<-mu_ij
pearson_value=0
for( i in 1:(nrow(pivot_table)-1)){
  for(j in 2:(ncol(pivot_table)-1)){
   pearson_table[i,j]<-(mu_ij[i,j]-pivot_table[i,j])**2/mu_ij[i,j]
   pearson_value=pearson_value+pearson_table[i,j]
  }
}
print(paste0("Value for X^2 (pearson's test) is ",pearson_value ))

#Log-likelihood ratio G^2
log_likelihood_table<-mu_ij
log_likelihood_value=0
for( i in 1:(nrow(pivot_table)-1)){
  for(j in 2:(ncol(pivot_table)-1)){
   log_likelihood_table[i,j]<-2*pivot_table[i,j]*log(pivot_table[i,j]/mu_ij[i,j])
   log_likelihood_value=log_likelihood_value+log_likelihood_table[i,j]
  }
}

print(paste0("Value for G^2 (Log-likelihood ratio test) is ",log_likelihood_value ))


```

$H_0: \pi_{ij}=\pi_{i+} \pi_{+j}$

$H_\alpha:$ at least one $\pi_{ij}\neq\pi_{i+} \pi_{+j}$

```{r}
critical_value=qchisq(p = .95, df = 2)
p_value_pearson=pchisq(q=44.2914329052853, df=2, lower.tail=FALSE)
p_value_log_likelihood=pchisq(q=54.0595809062812, df=2, lower.tail=FALSE)
if(pearson_value > critical_value){
  cat(paste("Result for pearson independence test under 95% C.I:  \nWe can reject H0 with p-value of pearson's test",p_value_pearson,". Diabetes outcomes are dependent on and BMI categories!\n"))
  
}else{
   cat("Result for pearson independence test under 95% C.I:  \nWe can't reject H0, and Diabetes outcomes and BMI categories are independent!\n")
}
```

```{r}
critical_value=qchisq(p = .95, df = 2)

if(log_likelihood_value > critical_value){
  cat(paste("Result for log likelihood ratio (LR) independence test under 95% C.I: \nWe can reject H0 with p-value of log-likelihood ratio test",p_value_log_likelihood,". Diabetes outcomes are dependent on and BMI categories!\n"))
}else{
   cat("We can't reject H0, and Diabetes outcomes and BMI categories are independent!")
}
```

```{r}
# Pearson's correlation test
df=pivot_table
df_filtered <- df[1:(nrow(df) - 1), 2:3]
print(df_filtered )

#Phi Coefficient
test <- chisq.test(df_filtered)
phi <- sqrt(test$statistic) / sum(df_filtered)
print(phi)
#cor.test(df_filtered$Diabetes, df_filtered$No_Diabetes, method = "pearson")
```

### ordinal residuals

```{r}
# Add v values directly to the data frame
# v values are group-wise means of BMI over BMI categories
diabetes.dat$BMI.mean <- ave(diabetes.dat$BMI, diabetes.dat$BMI.ord, FUN = mean)

# Ordinal categorical estimated correlation
r.BMI.mean.Outcome <- cor(diabetes.dat$BMI.mean, diabetes.dat$Outcome.val)
cat(paste0("Value for ordinal categorical estimated correlation between diabetes outcomes and BMI categories is ",r.BMI.mean.Outcome ))

# Exact estimated correlation
r.BMI.Outcome <- cor(diabetes.dat$BMI, diabetes.dat$Outcome.val)
cat(paste0("Value for exact estimated correlation between diabetes outcomes and BMI categories is ",r.BMI.Outcome ))

# These r values are not so much different from each other
if(abs(r.BMI.mean.Outcome - r.BMI.Outcome) / r.BMI.Outcome < 0.01){
  cat("Value for ordinal categorical estimated correlation and value for exact estimated correlation are not so much different from each other.\n")
}else{
   cat("Value for ordinal categorical estimated correlation and value for exact estimated correlation are not the same thing.\n")
}

# H0: rho = 0 vs. H1: rho not= 0
n <- nrow(diabetes.dat)
M <- (n - 1) * r.BMI.mean.Outcome ^ 2
p.value <- 1-pchisq(M, df = 1)
significance.level <- 0.001
if(p.value < significance.level){
  cat("Reject H0 at significance level 0.001. The population correlation between Diabetes outcomes and BMI categories is not 0. Diabetes outcomes are dependent on and BMI categories!\n")
}else{
   cat("We can't reject H0 at significance level 0.001. The population correlation between Diabetes outcomes and BMI categories is 0. Diabetes outcomes and BMI categories are independent!\n")
}
```


### Fisher Exact tests

```{r}
# Contingency table 
table_contingency <- table(diabetes.dat$BMI.ord, diabetes.dat$Outcome)
# Check if there's independence for all data
fisher_result <- fisher.test(table_contingency)
print(fisher_result)
```

```{r}
# Create 2x2 table to test the relationship between different BMI and diabetes 
# Test for the relationship between underweight and diabetes vs.other categories
non_under_no_diabetes <- sum(table_contingency["Healthy Weight", "No_Diabetes"]) +
                               sum(table_contingency["Overweight", "No_Diabetes"]) +
                               sum(table_contingency["Obesity", "No_Diabetes"])
non_under_diabetes <- sum(table_contingency["Healthy Weight", "Diabetes"]) +
                            sum(table_contingency["Overweight", "Diabetes"]) +
                            sum(table_contingency["Obesity", "Diabetes"])
under_vs_rest <- matrix(c(table_contingency["Underweight", "No_Diabetes"],non_under_no_diabetes,table_contingency["Underweight", "Diabetes"], non_under_diabetes),nrow = 2, dimnames = list("BMI" = c("Underweight", "Non_Underweight"),"Outcome" = c("No_Diabetes", "Diabetes")))
# Perform Fisher's Exact Test on underweight vs. others 2x2 table
fisher_result_underweight <- fisher.test(under_vs_rest)
print(fisher_result_underweight)
```
```{r}
# Test for the relationship between Healthy weight and other categories
non_healthy_no_diabetes <- sum(table_contingency["Underweight", "No_Diabetes"]) +
                               sum(table_contingency["Overweight", "No_Diabetes"]) +
                               sum(table_contingency["Obesity", "No_Diabetes"])
non_healthy_diabetes <- sum(table_contingency["Underweight", "Diabetes"]) +
                            sum(table_contingency["Overweight", "Diabetes"]) +
                            sum(table_contingency["Obesity", "Diabetes"])
healthy_vs_rest <- matrix(c(table_contingency["Healthy Weight", "No_Diabetes"],non_healthy_no_diabetes,table_contingency["Healthy Weight", "Diabetes"], non_healthy_diabetes),nrow = 2, dimnames = list("BMI" = c("Healthy", "Non_Healthy"),"Outcome" = c("No_Diabetes", "Diabetes")))
# Perform Fisher's Exact Test on underweight vs. others 2x2 table
fisher_result_healthy <- fisher.test(healthy_vs_rest)
print(fisher_result_healthy)
``` 

```{r}
# Test for the relationship between Overweight and other categories
non_over_no_diabetes <- sum(table_contingency["Underweight", "No_Diabetes"]) +
                               sum(table_contingency["Healthy Weight", "No_Diabetes"]) +
                               sum(table_contingency["Obesity", "No_Diabetes"])
non_over_diabetes <- sum(table_contingency["Underweight", "Diabetes"]) +
                            sum(table_contingency["Healthy Weight", "Diabetes"]) +
                            sum(table_contingency["Obesity", "Diabetes"])
over_vs_rest <- matrix(c(table_contingency["Overweight", "No_Diabetes"],non_over_no_diabetes,table_contingency["Overweight", "Diabetes"], non_over_diabetes),nrow = 2, dimnames = list("BMI" = c("Overweight", "Non_Overweight"),"Outcome" = c("No_Diabetes", "Diabetes")))
# Perform Fisher's Exact Test on underweight vs. others 2x2 table
fisher_result_over <- fisher.test(over_vs_rest)
print(fisher_result_over)
``` 

```{r}
# Test for the relationship between obesity and other categories
non_obesity_no_diabetes <- sum(table_contingency["Underweight", "No_Diabetes"]) +
                               sum(table_contingency["Healthy Weight", "No_Diabetes"]) +
                               sum(table_contingency["Overweight", "No_Diabetes"])
non_obesity_diabetes <- sum(table_contingency["Underweight", "Diabetes"]) +
                            sum(table_contingency["Healthy Weight", "Diabetes"]) +
                            sum(table_contingency["Overweight", "Diabetes"])
obesity_vs_rest <- matrix(c(table_contingency["Obesity", "No_Diabetes"],non_obesity_no_diabetes,table_contingency["Obesity", "Diabetes"], non_obesity_diabetes),nrow = 2, dimnames = list("BMI" = c("Obesity", "Non_Obesity"),"Outcome" = c("No_Diabetes", "Diabetes")))
# Perform Fisher's Exact Test on underweight vs. others 2x2 table
fisher_result_obesity <- fisher.test(obesity_vs_rest)
print(fisher_result_obesity)
``` 
```{r}
# Create a p-value and odds ratio table to visualize the relationship
p_values <- c(
  underweight_vs_others = fisher_result_underweight$p.value, 
  healthy_weight_vs_others = fisher_result_healthy$p.value, 
  overweight_vs_others = fisher_result_over$p.value, 
  obesity_vs_others = fisher_result_obesity$p.value
)
odds_ratio <- c(
  underweight_vs_others = fisher_result_underweight$estimate, 
  healthy_weight_vs_others = fisher_result_healthy$estimate, 
  overweight_vs_others = fisher_result_over$estimate, 
  obesity_vs_others = fisher_result_obesity$estimate
)
# Create a data frame with the p-values
results_table <- data.frame(
  Odds_ratio = odds_ratio ,
  P_Value = p_values
)
row.names(results_table) <- c("Underweight vs Others", "Healthy Weight vs Others", "Overweight vs Others", "Obesity vs Others")
# Print the table
print(results_table)
```

### logistic regression (if approved by professor, TBD)

```{r}

diabetes.dat %>% head()
model_full <- glm(factor(Outcome) ~ ., data = diabetes.dat, family = 'binomial')
summary(model_full)
```

```{r}
model1 <- glm(factor(Outcome) ~ BMI, data = diabetes.dat, family = 'binomial')
summary(model1)
```

### Confounding Variable -- Age
```{r}

```

```{r}
sessionInfo()
```
